### ISSUE TITLE
Issuing VCs to different identifiers

### ISSUE THREAD

**Issue by alenhorvat** [tlodderstedt/openid-connect-4-credential-issuance#1]
Does the mDL describe how they prevent 1 credential to be issued to different entities?
_batch issuance of multiple credentials of the same type bound to different key material (see mDL)_

For example, how to prevent that I ask an eID issuance to 2 DIDs, where 1 is owned by me and another by someone else? (Issuer cannot know where "my" keys reside)

Extreme scenario:
- I authenticate using classical means
- I share additional VCs, e.g., issued to DID A and DID B
- I ask for a batch VC issuance to DIDs C, D (where I don't necessarily own both) - In theory, I can share the access token with other parties to create a bindable proof.

If I understand correctly, user authentication/identification is a business process performed at step (3) User Login and consent.

Question(s)/Remark(s)
1. Is this a problem that should be solved/mitigated at the protocol level or at the business layer?
2. Are wallet audits and/or certifications crucial to prevent this?
3. It is crucial that the wallet communicates with an issuer directly (so it can verify the TLS cert) (covered in the OIDC specs);
4. Having a reliable list of issuers is crucial -- if the issuer list curated by the wallet publisher is modified by a rogue actor, wallet communication may be proxied (MITM) and an eID could be issued to the attacker's DID.

**Comment by tlodderstedt** [comment]
I'm not sure what problem you refer to. The binding between holder and credential shall be ensured by the binding proofs in step 6. A holder can control many different keys/DIDs, whether a DID or key belongs to a holder is outside of the scope of the specification. All key material a respective user presents a proof for is considered belonging to her.

**Comment by Sakurann** [comment]
The protocol need to ensure that the entity requesting the issuance of a credential can prove that it "controls" the DIDs it is requesting the credential to be bound to. Whether those DIDs are "owned" by that requesting entity would out of scope.

**Comment by alenhorvat** [comment]
Clear. This is out of scope. I'm closing the issue.
