### ISSUE TITLE
Can code hash be used as a challenge to bind proofs instead of access_token hash..?

### ISSUE THREAD

**Issue by Sakurann** [tlodderstedt/openid-connect-4-credential-issuance#9]
This would mean credential will be issued from the Token Endpoint and access_token will be returned alongside credential or acceptance_token.
Something intuitively tells me that this is not a good idea, but I think still worth clarifying.

**Comment by tlodderstedt** [comment]
I see issuance of credentials with the token response as an optimization of the protocol for some situations we still need to understand. So I would like to limit issuance on the credential endpoint now (as suggested by DW) and optimize when we have implementation experience.

**Comment by tlodderstedt** [comment]
we agreed to use dedicated nonces instead of hashes of other protocol parameters
